# Generated by Django 5.0.4 on 2024-06-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='contenido',
            new_name='referencia',
        ),
    ]
